name: test-solar-system

on:
  pull_request:
    branches:    
      - master
      - dev
  workflow_dispatch:

jobs:
  test-solar-system:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print current working directory
        run: pwd

      - name: List all files
        run: ls         

      - name: Debugging - Print Python path
        run: python -c "import sys; print(sys.path)"

      - name: Debugging - List files and permissions
        run: |
          ls -l
          stat planet.py

      - name: run the tests
        run: pytest tests/

